Time fixes
RedHatInsights/edge-frontend pull request #314
Opened 2022-02-03 08:03 UTC by Avielyo10

# Description

Backend changed the CreatedAt/UpdatedAt fields from `time.Time` to `sql.NullTime`.

This caused an `Invalid date` since now each field is now a struct with 2 fields, e.g: 
```
"CreatedAt":{"Time":"2021-12-22T19:20:27.53471Z","Valid":true}
```

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

2022-02-03 12:17 UTC, biancarosa approved these changes

2022-02-03 17:30 UTC, matoval requested changes
It looks like these changes are no longer needed since Edge-api [PR#597 ](https://github.com/RedHatInsights/edge-api/pull/597)was merged.

2022-02-03 18:51 UTC, Avielyo10 commented
Well the PR merged not solves this. It only allows nullable time on CreatedAt/UpdatedAt. 

Still those fields will have 2 fields each. This has to be merged to solve this issue.

2022-02-07 09:10 UTC, Avielyo10 commented
seems like the time is now back to track, closing

2022-02-07 09:10 UTC, closed without merging