Unlink repository message - new flow
RedHatInsights/edge-frontend pull request #473
Opened 2022-06-09 23:40 UTC by adeliaferreira

# Description

Add new component and message to unlink repository flow

Fixes THEEDGE-1585

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `npm run lint:js:fix` to check that my code is properly formatted

2022-06-09 23:42 UTC, adeliaferreira commented
quick comment: On this PR, there's a style tag on component due to a lack of responsive on component CSS, due to component been rendered inside data-driven framework, the responsive align is not working well, due it, I override the css property from PF4, let me know if you have a better solution for this problem.

2022-06-13 07:46 UTC, boaz0 approved these changes

2022-06-13 07:46 UTC, boaz0 commented on src/Routes/ImageManager/steps/customPackage.js
> +        style={{ '--pf-c-content--h4--MarginTop': 0 }} //due to component's lack of responsive need to override property
Awesome!

2022-06-13 15:47 UTC, resoluteCoder requested changes
Blocking PR due to required changes for required functionality

2022-06-14 13:29 UTC, adeliaferreira commented
After check with Og and my squad, for now, we'll merge the current PR and handle the changes as improvements, I'm already working on it, but to avoid delay the delivery for it, we'll follow Andy's recommendation to move on with this feature and handle it in a improvement ticket, once all changes are finish, I'll raise a new PR

2022-06-14 13:29 UTC, merged

2022-06-14 16:06 UTC, omaciel commented
fwiw, I was not aware of the "block" comment and I have zero influence over what gets merged or not. A PR needs to be reviewed and approved by peers, and it is only then that it should be merged. I assume the concerns have been addressed before it got merged?