Fix table sorting after modal submit
RedHatInsights/edge-frontend pull request #537
Opened 2022-09-01 16:53 UTC by tpapaioa

# Description

After submitting a modal (add to group, remove from group, or update) from the Systems page, the refreshed table is sorted by name instead of by "Last seen", which is the default. Also, the "Last seen" column header is still highlighted, as if the table is still sorted by that column.

Similar behavior can be seen on the Groups, Repositories, and Images pages too.

This PR fixes this issue by setting {{hasModalSubmitted}} when modals have submitted, and re-running the relevant query w/ the correct sort and pagination query params in {{GeneralTable}} when this state variable has changed.

Fixes # (issue)

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `npm run lint:js:fix` to check that my code is properly formatted

2022-09-02 01:01 UTC, matoval commented
I think we can resolve this issue with default queries in the api files. We are doing this for the image table api calls:  https://github.com/RedHatInsights/edge-frontend/blob/master/src/api/images/index.js#L73

2022-09-02 13:14 UTC, tpapaioa commented
> I think we can resolve this issue with default queries in the api files. We are doing this for the image table api calls: https://github.com/RedHatInsights/edge-frontend/blob/master/src/api/images/index.js#L73

That would work for the default parameters, but not if the user has changed the sort/pagination/filter settings. After submitting the modal, those settings are still displayed, but the displayed table data don't respect those settings prior to this fix.

2022-09-03 04:45 UTC, matoval requested changes

2022-09-03 04:45 UTC, matoval commented on src/Routes/Devices/Inventory.js
> +    setTimeout(() => setHasModalSubmitted(true), 800);
We should replace all setTimeout with async/await this way we don't have to set a hard coded wait time.

2022-09-03 04:45 UTC, matoval commented on src/components/general-table/GeneralTable.js
> +  }, [chipsArray, perPage, page, sortBy, hasModalSubmitted]);
Adding hasModalSubmitted is causing a double render, once when it's set to true and another when it's set back to false.

2022-09-07 15:26 UTC, resoluteCoder approved these changes
We can merge but we can create a bug ticket to remove the double render. At least this will fix a user impacting bug. Good job @tpapaioa

2022-09-07 15:26 UTC, matoval approved these changes

2022-09-07 15:46 UTC, merged