Added eslint file for cypress tests
RedHatInsights/edge-frontend pull request #558
Opened 2022-09-26 22:51 UTC by de1987

# Description

- Added eslint file for cypress tests
- Added retry pop tests for system details
- Changed service timed out description as described in the mockups Added ids for status and retry popover components
- Added fixtures for cypress tests
- Fixed modal cookie acceptance on cypress tests
- Lint retry popover system tests

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

2022-09-26 22:57 UTC, de1987 commented on cypress/support/commands.js
> +      cy.wrap(body).find('a.call').click().wait(2000)
modal cookie agreement was being accepted, it was an intermittent issue when running cypress tests

2022-09-26 22:58 UTC, de1987 commented on src/Routes/Devices/RetryUpdatePopover.js
> +      ? 'The service timed out during the last update. You can retry the update or build a new one.'
minor text fixes as described in the mockups.

2022-09-27 20:28 UTC, tpapaioa requested changes
Please put explanatory comments in the code instead of in PR comments.
Also, what is the reason for setting the lint config to remove semicolons?

2022-09-29 20:11 UTC, de1987 commented
> Please put explanatory comments in the code instead of in PR comments. Also, what is the reason for setting the lint config to remove semicolons?

It's done.

It's removing the semicolons is only for cypress tests code, and I added it because the old cypress tests are without semicolons.
@matoval @resoluteCoder explained we don't need to use semicolons for javascript, the idea here it's to keep the code uniform.

2022-10-03 17:54 UTC, de1987 commented
@tpapaioa done

2022-11-07 18:34 UTC, tpapaioa approved these changes

2022-11-11 21:01 UTC, resoluteCoder approved these changes

2022-11-11 21:17 UTC, merged