THEEDGE-2466 - Breadcrumbs aren't correct when going from groups to devices
RedHatInsights/edge-frontend pull request #612
Opened 2022-11-22 20:34 UTC by acruzgon

# Description

When clicking on a device name link from the group details page the breadcrumbs show systems but should show group name.
This PR is moving from  Systems > { System name } to { Group name } > { System name }

Fixes # (issue)
https://issues.redhat.com/browse/THEEDGE-2466

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Tests update

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `npm run lint:js:fix` to check that my code is properly formatted

2022-11-22 21:38 UTC, acruzgon commented
/retest

2022-11-24 03:59 UTC, tpapaioa requested changes

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/DeviceDetail/DeviceDetail.js
> +import { useParams, useLocation, useHistory } from 'react-router-dom';
Combine with the `Link` import on line 2. Also, `useLocation` isn't needed (see comments below).

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/DeviceDetail/DeviceDetail.js
> +  const groupName = location?.state?.GroupName;
```suggestion
  const history = useHistory();
  const { prevPath, groupName } = history.location?.state || {};
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/DeviceDetail/DeviceDetail.js
> +        {!groupsPrevPath ? (
```suggestion
        {!groupName ? (
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/DeviceDetail/DeviceDetail.js
> +              <Link to="/inventory">Systems</Link>
```suggestion
              <Link to={paths['inventory']}>Systems</Link>
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/DeviceDetail/DeviceDetail.js
> +          <Breadcrumb ouiaId="systems-list">
```suggestion
          <Breadcrumb ouiaId="groups-list">
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/DeviceDetail/DeviceDetail.js
> +            <BreadcrumbItem> {groupName}</BreadcrumbItem>
```suggestion
            <BreadcrumbItem>
              <Link to={prevPath}>{groupName}</Link>
            </BreadcrumbItem>
            <BreadcrumbItem isActive>
              <div className="ins-c-inventory__detail--breadcrumb-name">
                {entity?.display_name || <Skeleton size={SkeletonSize.xs} />}
              </div>
            </BreadcrumbItem>
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/Devices/DeviceTable.js
> +import { Link, useHistory, useLocation } from 'react-router-dom';
```suggestion
import { Link, useHistory } from 'react-router-dom';
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/Devices/DeviceTable.js
> +  const location = useLocation();
```suggestion
const createRows = (devices, hasLinks, fetchDevices, groupName, history) => {
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/Devices/DeviceTable.js
> +                state: { prevPath: location.pathname, GroupName: groupName },
```suggestion
                state: { prevPath: history.location.pathname, groupName },
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/Devices/DeviceTable.js
> +            groupName
```suggestion
            groupName,
            history
```

2022-11-24 03:59 UTC, tpapaioa commented on src/Routes/Devices/DeviceTable.js
> +  const location = useLocation();
In general, hooks should be called only at the beginning of component functions, not in other functions.

2022-11-24 04:05 UTC, tpapaioa commented
If I refresh the system details page after clicking on it from the group details page, the breadcrumb changes to the default "Systems > [system name]".

2022-12-06 14:03 UTC, tpapaioa approved these changes

2022-12-06 18:13 UTC, matoval approved these changes

2022-12-06 18:13 UTC, resoluteCoder approved these changes
Muy Excellente :tada:

2022-12-06 18:14 UTC, merged