THEEDGE-2929
RedHatInsights/edge-frontend pull request #619
Opened 2022-12-15 18:27 UTC by acruzgon

# Description

Currently, `handleClose` event in `UpdateVersionTable.js` is hardcoding to go back to inventory page every time an update is trigger. That's not the case when updating from system details page or group details page. This PR is changing `handleClose` to redirect to previous correct page using `history.goBack()` instead of `history.push()
`

Fixes # (issue)
[THEEDGE-2929](https://issues.redhat.com/browse/THEEDGE-2929)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [X] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

2022-12-15 18:42 UTC, pavankrao commented
Functionality works as expected. I have tested on my local front end

2022-12-16 19:15 UTC, tpapaioa approved these changes

2022-12-16 21:12 UTC, tpapaioa requested changes
Using `go()` doesn't work if the user directly entered the URL in the browser. Clicking back / Update / Cancel takes the user back to the default browser page instead of to the expected path.

2022-12-22 13:51 UTC, tpapaioa approved these changes

2022-12-28 19:37 UTC, matoval approved these changes

2022-12-28 19:54 UTC, merged