Theedge 3284 expose inventory
RedHatInsights/edge-frontend pull request #676
Opened 2023-05-04 01:10 UTC by acosferreira

# Description

expose inventory and image  component
Fix initial conflict reactdom@v5 x v6

Fixes # (THEEDGE-3284)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

2023-05-17 22:12 UTC, loadtheaccumulator approved these changes
lgtm

2023-05-18 00:54 UTC, matoval requested changes

2023-05-18 00:54 UTC, matoval commented on config/dev.webpack.config.js
> +        { 'react-router-dom': { singleton: true, requiredVersion: '*' } },
This line is causing edge-frontend to fail to load. The error it returns is : 
```
Uncaught Error: You cannot render a <Router> inside another <Router>. You should never have more than one in your app
```
The solution I found is replacing this line with this:
```suggestion
        { 'react-router-dom': { requiredVersion: deps['react-router-dom'] } },
```

2023-05-18 00:54 UTC, matoval commented on src/Routes/ImageManager/Images.js
> +    : useHistory();
I don't think we should use navigate in this var. We should return null if history isn't available.
```suggestion
 const history = historyProp
    ? historyProp()
    : useHistory
    ? useHistory()
    : null;
```

2023-05-18 00:54 UTC, matoval commented on src/Routes/ImageManager/Images.js
> +  const navigate = navigateProp ? navigateProp() : useNavigate();
We should return null when navigate isn't available
```suggestion
  const navigate = navigateProp ? navigateProp() : useNavigate ? useNavigate() : null;
```

2023-05-18 00:54 UTC, matoval commented on src/Routes/ImageManager/Images.js
> +      history.push({ a });
We need to remove the curly braces:
```suggestion
      history.push(a);
```

2023-05-18 00:54 UTC, matoval commented on src/Routes/Devices/DeviceTable.js
> +            pathname: `/${rowData.rowInfo.id}/update`,
The commented out code below this line should be used instead of this line, deviceBaseUrl is needed to open update device page

2023-05-18 22:21 UTC, matoval approved these changes

2023-05-18 22:21 UTC, matoval approved these changes

2023-05-19 22:06 UTC, merged