update document link in image table
RedHatInsights/edge-frontend pull request #702
Opened 2023-07-02 07:52 UTC by mgold1234

# Description
update the document link in the image table when image table is empty

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

2023-07-04 11:39 UTC, adeliaferreira approved these changes
Lgtm

2023-07-05 16:18 UTC, loadtheaccumulator commented
@mgold1234 Is this based on a ticket resulting from UXD/Documentation discussion? Please add the ticket # to fixes in description and update the ticket with the discussion.

2023-07-05 16:20 UTC, loadtheaccumulator requested changes
feature flag question

2023-07-05 16:20 UTC, loadtheaccumulator commented on src/Routes/ImageManager/ImageSetsTable.js
> +              link: 'https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_installing_and_managing_rhel_for_edge_images/index',
@mgold1234 Should this be feature-flagged with the switch over, or a permanent change needed now?

2023-07-05 18:29 UTC, loadtheaccumulator commented
This change doesn't appear to  point to documentation relevant to Edge Management.

2023-07-05 18:37 UTC, loadtheaccumulator commented
This is specific to on-prem and not Edge Management. I'm closing this PR to avoid it being merged inadvertently.

2023-07-05 18:37 UTC, closed without merging