change the look and feel of empty state
RedHatInsights/edge-frontend pull request #718
Opened 2023-07-24 08:14 UTC by mgold1234

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

2023-07-24 14:43 UTC, acosferreira approved these changes
lgtm

2023-07-24 15:25 UTC, loadtheaccumulator requested changes
Checking source of the links. I'm not sure they should be RHEL 8.

2023-07-24 15:25 UTC, loadtheaccumulator commented on src/Routes/ImageManager/ImageSetsTable.js
> +              link: 'https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/composing_installing_and_managing_rhel_for_edge_images/index#introducing-rhel-for-edge-images
Is this the correct link?

2023-07-24 15:25 UTC, loadtheaccumulator commented on src/Routes/ImageManager/__snapshots__/ImageSetsTable.test.js.snap
> +            href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/composing_installing_and_managing_rhel_for_edge_images/index#introducing-rhel-for-edge-images_co
Is this the correct link?

2023-07-24 15:25 UTC, loadtheaccumulator commented on src/Routes/ImageManager/__snapshots__/ImageSetsTable.test.js.snap
> +            href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/composing_installing_and_managing_rhel_for_edge_images/index#introducing-rhel-for-edge-images_co
Is this the correct link?

2023-07-24 18:49 UTC, loadtheaccumulator commented on src/Routes/ImageManager/__snapshots__/ImageSetsTable.test.js.snap
> +            href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/composing_installing_and_managing_rhel_for_edge_images/index#introducing-rhel-for-edge-images_co
The reason I ask about the doc URL is the current version of the OS RHEL 9, and these links map to RHEL 8.

2023-07-24 18:59 UTC, acosferreira commented
> Checking

The link to RHEL9 seems be https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/composing_installing_and_managing_rhel_for_edge_images/index#introducing-rhel-for-edge-images_composing-installing-managing-rhel-for-edge-images

Can we check with doc team?

2023-07-26 16:13 UTC, loadtheaccumulator approved these changes

2023-07-26 16:13 UTC, merged