Distribution mapper
RedHatInsights/edge-frontend pull request #84
Opened 2021-07-08 23:39 UTC by matoval

Changed releaseMapper to match design mockup and used it to make distribution column more human readable.

2021-07-09 05:20 UTC, boaz0 reviewed
Hey @matoval , can you provide more information why this change is necessary?
Thanks.

2021-07-09 05:23 UTC, matoval commented
We are using this mapper for both the image wizard and the manage images table. In the image wizard we are using the longer value and in the table we are using the shorter value.

2021-07-09 06:54 UTC, matoval commented
I just realized this isn't going to solve the issue in the wizard. I will push a new commit with the correct solution.

2021-07-11 06:09 UTC, boaz0 requested changes
Small changes but all in all LGTM

2021-07-11 06:09 UTC, boaz0 commented on src/Routes/ImageManager/Images.js
> +                                title: releaseMapper[`${item?.Distribution}-short`],
Revert this change and use `distributionMapper`:
```js
  title: distributionMapper[item?.Distribution],
```

2021-07-11 06:09 UTC, boaz0 commented on src/Routes/ImageManager/steps/imageOutput.js
> +      initialValue: 'rhel-84',
create a new constant called DEFAULT_RELEASE and use it here:
```js
const DEFAULT_RELEASE ='rhel-84';
....
initialValue: DEFAULT_RELEASE
```

2021-07-11 06:09 UTC, boaz0 commented on src/Routes/ImageManagerDetail/constants.js
> +  'rhel-84-short': 'RHEL 8.4',
Remove this one. And create a new mapper called `distributionMapper`:
```js
export const distributionMapper = {
  'rhel-84': 'RHEL 8.4',
}

export const releaseMapper = {
  'rhel-84': 'Red Hat Enterprise Linux (RHEL) 8.4',
}
```

2021-07-11 09:35 UTC, boaz0 approved these changes
Flawless LGTM :100:

2021-07-11 09:37 UTC, merged