Added action to open update image wizard component using table actions
RedHatInsights/edge-frontend pull request #98
Opened 2021-07-15 22:57 UTC by matoval

Added action to open update image wizard component using table actions. If an image has a status of success show update action.

2021-07-19 07:32 UTC, boaz0 commented
@matoval today your team mate @resoluteCoder is going to review your PR.
If you need help with resolving conflicts - lemme know I will be happy to help you.
Again sorry for blocking you with this.

2021-07-19 23:45 UTC, resoluteCoder approved these changes
Looks good :+1:

2021-07-20 06:20 UTC, boaz0 commented
@matoval there is conflicts. can you rebase? 
@resoluteCoder after this PR will be conflict resolved, please review this again.

Thanks.

2021-07-20 15:35 UTC, boaz0 requested changes
Why not changing

2021-07-20 15:35 UTC, boaz0 commented on src/Routes/ImageManager/ImageTable.js
> +          <SimpleListItem
I think `Text` is better https://www.patternfly.org/v4/components/text

```js
<Text component="a" href={rowData.isoURL} ...>Download</Text> 
```

2021-07-20 15:35 UTC, boaz0 commented on src/Routes/ImageManager/ImageTable.js
> +  setUpdateImageID,
can we create openUpdateWizard that will both open the update wizard and set the update image ID?

2021-07-20 17:24 UTC, boaz0 approved these changes

2021-07-20 17:25 UTC, merged

2021-07-20 17:26 UTC, boaz0 commented
@matoval small nitpick request - make your commit message less than 71 characters.
Thanks.